Update android_build.yml

diff --git a/.github/workflows/android_build.yml b/.github/workflows/android_build.yml
--- a/.github/workflows/android_build.yml
+++ b/.github/workflows/android_build.yml
@@ -25,18 +25,18 @@ jobs:
       - name: Download Godot 4.3.1 Headless
         if: steps.cache.outputs.cache-hit != 'true'
         run: |
-          wget --tries=3 --waitretry=5 https://github.com/godotengine/godot/releases/download/4.3.1-stable/Godot_v4.3.1-stable_linux.x86_64.zip -O godot.zip || \
+          wget --tries=3 --waitretry=5 https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip -O godot.zip || \
           unzip godot.zip
-          mv Godot_v4.3.1-stable_linux.x86_64 godot
+          mv Godot_v4.4.1-stable_linux.x86_64 godot
           chmod +x godot
 
       - name: Download Android Export Templates
         if: steps.cache.outputs.cache-hit != 'true'
         run: |
-          wget --tries=3 --waitretry=5 https://github.com/godotengine/godot/releases/download/4.3.1-stable/Godot_v4.3.1-stable_export_templates.tpz -O templates.tpz || \
-          wget --tries=3 --waitretry=5 https://downloads.tuxfamily.org/godotengine/4.3.1/Godot_v4.3.1-stable_export_templates.tpz -O templates.tpz || { echo "Download failed from all mirrors"; exit 1; }
-          mkdir -p ~/.local/share/godot/export_templates/4.3.1.stable
-          tar -xvf templates.tpz -C ~/.local/share/godot/export_templates/4.3.1.stable
+          wget --tries=3 --waitretry=5 https://github.com/godotengine/godot/releases/download/4.4.1-stable/Godot_v4.3.1-stable_export_templates.tpz -O templates.tpz || \
+          wget --tries=3 --waitretry=5 https://downloads.tuxfamily.org/godotengine/4.3.1/Godot_v4.4.1-stable_export_templates.tpz -O templates.tpz || { echo "Download failed from all mirrors"; exit 1; }
+          mkdir -p ~/.local/share/godot/export_templates/4.4.1.stable
+          tar -xvf templates.tpz -C ~/.local/share/godot/export_templates/4.4.1.stable
 
       - name: Restore Keystore
         run: |
